version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: crisiscleanup
      POSTGRES_PASSWORD: crisiscleanup
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    entrypoint: /crisiscleanup/docker-entrypoint.sh
    env_file: .env
    environment:
      RAILS_ENV: docker
    volumes:
      - .:/crisiscleanup
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
